import Head from 'next/head';


export default function Contact() {
  return (
    <div className={''}>
      <Head>
        <title>Contact Us!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main className={''}>

       This is the contact pag
     </main>
    </div>
  )
}
