import Head from 'next/head';
import styles from '../styles/Contact.module.css'

export default function Contact() {
  return (
    <div className={''}>
      <Head>
        <title>Contact Us!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main className={styles.contact}>

       This is the contact pag
     </main>
    </div>
  )
}
