import { useEffect, useState } from 'react'
import Head from 'next/head'
import { useTheme, makeStyles } from '@material-ui/core/styles'
import styles from '../../styles/Home.module.css'
import {AppBar, Box, Button, Container, Grid, IconButton, Paper, Toolbar, Typography } from '@material-ui/core'
import MenuIcon from '@material-ui/icons/Menu'
import Image from 'next/image'




const Home =({imageURL,children})=> {

const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
  },
  menuButton: {
    marginRight: theme.spacing(2),
  },
  title: {
    flexGrow: 1
  },
  appBar: {
    backgroundColor: theme.palette.primary.main,

  },
  hero: {
    border: `3px solid ${theme.palette.primary.dark}`,
    backgroundColor: theme.palette.primary.light,
    backgroundImage: `url(${imageURL})`,
    height: '100vh',
    width: '100vw'
  }

}));

  const theme = useTheme()
  const classes = useStyles();



  return (
    <div className={''}>
      <Head>
        <title>Frank Craven ReMAX</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      <div className={classes.root}>
        <AppBar position="static" color='primary' className={classes.appBar}>
          <Toolbar>
            <IconButton edge="start" className={classes.menuButton} color="inherit" aria-label="menu">
              <MenuIcon />
            </IconButton>
            <Typography variant="h6" className={classes.title}>
              Welcome
            </Typography>
            <Button color="inherit">Buy</Button>
            <Button color="inherit">Rent</Button>
            <Button color="inherit">Sell</Button>
            <Button color="inherit">Search</Button>
          </Toolbar>
        </AppBar>

        <Container>
          <Grid container>

            <Grid item className={classes.hero}>
            </Grid>
          </Grid>
        </Container>




      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://projectzeusbackend.herokuapp.com/api/images')
  const data = await res.json()
  return { props: { imageURL: data } }
}


export default Home;
