import Head from 'next/head';
import Link from 'next/link'
import axios from 'axios'


function LocationById({ data }) {

 console.log('Location By Id data -=> ', data)
  return (
    <div className={''}>
      <Head>
        <title>Contact Us!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main className={''}>
       <Link href='/locations'>
       <a>Back to All Locations</a>
       </Link>
       <h1>{data.location}</h1>
       <p>{data.summary}</p>
     </main>
    </div>
  )
}


export async function getServerSideProps(context) {
  const { location } = context.params
  const { data } = await axios.get(`https://projectzeusbackend.herokuapp.com/api/locations/${location}`)
  return { props: {data}}
}

export default LocationById
